# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: wallet.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'wallet.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cwallet.proto\x12\x06wallet\"\'\n\x11GetBalanceRequest\x12\x12\n\naccount_id\x18\x01 \x01(\t\"=\n\x12GetBalanceResponse\x12\x15\n\rbalance_minor\x18\x01 \x01(\x03\x12\x10\n\x08\x63urrency\x18\x02 \x01(\t\"\x7f\n\x0bTransaction\x12\n\n\x02id\x18\x01 \x01(\t\x12\x14\n\x0c\x61mount_minor\x18\x02 \x01(\x03\x12\x10\n\x08\x63urrency\x18\x03 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x04 \x01(\t\x12\x11\n\ttimestamp\x18\x05 \x01(\x03\x12\x14\n\x0c\x63ounterparty\x18\x06 \x01(\t\";\n\x16GetTransactionsRequest\x12\x12\n\naccount_id\x18\x01 \x01(\t\x12\r\n\x05\x63ount\x18\x02 \x01(\x05\"D\n\x17GetTransactionsResponse\x12)\n\x0ctransactions\x18\x01 \x03(\x0b\x32\x13.wallet.Transaction2\xa8\x01\n\rWalletService\x12\x43\n\nGetBalance\x12\x19.wallet.GetBalanceRequest\x1a\x1a.wallet.GetBalanceResponse\x12R\n\x0fGetTransactions\x12\x1e.wallet.GetTransactionsRequest\x1a\x1f.wallet.GetTransactionsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'wallet_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETBALANCEREQUEST']._serialized_start=24
  _globals['_GETBALANCEREQUEST']._serialized_end=63
  _globals['_GETBALANCERESPONSE']._serialized_start=65
  _globals['_GETBALANCERESPONSE']._serialized_end=126
  _globals['_TRANSACTION']._serialized_start=128
  _globals['_TRANSACTION']._serialized_end=255
  _globals['_GETTRANSACTIONSREQUEST']._serialized_start=257
  _globals['_GETTRANSACTIONSREQUEST']._serialized_end=316
  _globals['_GETTRANSACTIONSRESPONSE']._serialized_start=318
  _globals['_GETTRANSACTIONSRESPONSE']._serialized_end=386
  _globals['_WALLETSERVICE']._serialized_start=389
  _globals['_WALLETSERVICE']._serialized_end=557
# @@protoc_insertion_point(module_scope)
